import {decodeSession} from '../../lib-threads-session.js';
const API='https://graph.threads.net/v1.0',WINDOW=2*24*60*60*1000,MAX_HISTORY=10;
async function graph(path,token){const sep=path.includes('?')?'&':'?';const r=await fetch(`${API}${path}${sep}access_token=${encodeURIComponent(token)}`,{headers:{Accept:'application/json'}});const body=await r.json().catch(()=>({}));return {ok:r.ok,body}}
async function next(url,token){const u=new URL(url);if(!u.searchParams.has('access_token'))u.searchParams.set('access_token',token);const r=await fetch(u,{headers:{Accept:'application/json'}});const body=await r.json().catch(()=>({}));return {ok:r.ok,body}}
function rel(v){if(v==null)return null;if(typeof v==='string'||typeof v==='number')return String(v);return v?.id?String(v.id):v?.data?.id?String(v.data.id):null}
async function history(token){const map=new Map();let p=await graph(`/me/replies?fields=${encodeURIComponent('id,text,timestamp,replied_to')}&limit=50`,token),pages=0;while(p.ok&&pages<MAX_HISTORY){pages++;for(const x of (p.body?.data||[])){const id=rel(x?.replied_to);if(id&&!map.has(id))map.set(id,{id:x?.id||null,text:x?.text||'',timestamp:x?.timestamp||null})}const n=p.body?.paging?.next;if(!n)break;p=await next(n,token)}return {ok:p.ok||pages>0,pages,map}}
function type(text=''){const t=String(text).trim().toLowerCase();if(/(광고|홍보|대출|투자|텔레그램|카톡|오픈채팅|http:\/\/|https:\/\/)/.test(t))return 'SPAM';if(/(씨발|시발|병신|개새|꺼져|좆|ㅅㅂ)/.test(t))return 'ABUSE';if(/[?？]|어디|어떻게|뭐야|무엇|알려|가능/.test(t))return 'QUESTION';if(/스하리/.test(t))return 'STHARI';if(/반하리/.test(t))return 'BANHARI';if(/또하리/.test(t))return 'TTOHARI';if(/고마|감사|예쁘|멋지|좋네|좋다|최고/.test(t))return 'COMPLIMENT';if(/안녕|반가|하이|ㅎㅇ/.test(t))return 'GREETING';if(t.length<=2)return 'SHORT';return 'NORMAL'}
const pools={STHARI:['스하리 좋아요 😆🙌','스하리 가자아 😎✨','스하리 확인했어요 😄🔥'],BANHARI:['반하리 완료 😆🙌','나도 반하리 😄✨','반하리 반가워요 😎💚'],TTOHARI:['또하리 환영 😆✨','또하리 좋아요 😄🙌','또 놀러와요 😆💚'],COMPLIMENT:['고마워요 😆🫶','좋게 봐줘서 고마워요 😄✨','나도 고마워요 🙌💚'],GREETING:['반가워요 😆🙌','오늘도 반가워요 😄✨','어서와요 😎💚'],SHORT:['응응 😆🙌','좋아요 😄✨','고마워요 😎💚'],NORMAL:['고마워요 😆🙌','응응 좋아요 😄✨','반가워요 😎💚','좋지요 😆🔥'],QUESTION:['응응 확인해볼게요 😄🙌','좋은 질문이에요 😆✨','맞아요 이 부분 많이 궁금해하시더라고요 😄🔥']};
function suggestion(t,id){const a=pools[t]||pools.NORMAL;let n=0;for(const c of String(id))n=(n*31+c.charCodeAt(0))>>>0;return a[n%a.length]}
export default async function handler(req,res){res.setHeader('Cache-Control','no-store');if(req.method!=='GET')return res.status(405).json({ok:false,error:'METHOD_NOT_ALLOWED'});const s=decodeSession(req);if(!s?.accessToken)return res.status(401).json({ok:false,error:'THREADS_NOT_CONNECTED'});const ids=[...new Set(String(req.query.post_ids||'').split(',').map(x=>x.trim()).filter(Boolean))].slice(0,10);if(!ids.length)return res.status(400).json({ok:false,error:'POST_IDS_REQUIRED'});const me=await graph('/me?fields=id,username',s.accessToken);if(!me.ok)return res.status(502).json({ok:false,error:'THREADS_ME_FAILED'});const h=await history(s.accessToken),mine=String(me.body.username||'').toLowerCase(),items=[],failures=[];for(const postId of ids){const r=await graph(`/${encodeURIComponent(postId)}/replies?fields=${encodeURIComponent('id,text,username,timestamp,permalink')}&limit=100`,s.accessToken);if(!r.ok){failures.push(postId);continue}for(const x of (r.body?.data||[])){if(String(x.username||'').toLowerCase()===mine)continue;const ts=Date.parse(String(x.timestamp||''));if(!Number.isFinite(ts)||ts<Date.now()-WINDOW)continue;const id=String(x.id||''),t=type(x.text||''),my=h.map.get(id)||null;items.push({id,post_id:postId,text:x.text||'',username:x.username||null,timestamp:x.timestamp||null,permalink:x.permalink||null,category:t,review_required:t==='SPAM'||t==='ABUSE',already_replied:Boolean(my),my_reply:my,suggestion:t==='SPAM'||t==='ABUSE'?'':suggestion(t,id)})}}items.sort((a,b)=>String(b.timestamp||'').localeCompare(String(a.timestamp||'')));return res.status(200).json({ok:true,window_days:2,count:items.length,unanswered_count:items.filter(x=>!x.review_required&&!x.already_replied).length,replied_count:items.filter(x=>x.already_replied).length,review_count:items.filter(x=>x.review_required&&!x.already_replied).length,reply_history_available:h.ok,reply_history_pages:h.pages,failures,items})}
