/* Local preview cache, owned temporary uploads and opt-in verified cleanup. */
(function(root){
'use strict';
const DB='pt_local_media_v1',ALIASES='pt_local_media_aliases_v1',OWNER='pt_temp_media_owner_v1';
const previews=new Map(),inflight=new Map();let db;
const tabId=crypto.randomUUID();
const aliases=()=>JSON.parse(localStorage.getItem(ALIASES)||'{}');
const owner=()=>{let id=localStorage.getItem(OWNER);if(!id){id=crypto.randomUUID();localStorage.setItem(OWNER,id)}return id};
function database(){return db||(db=new Promise((resolve,reject)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.createObjectStore('files',{keyPath:'id'});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)}))}
async function operation(mode,run){const d=await database();return new Promise((resolve,reject)=>{const tx=d.transaction('files',mode),r=run(tx.objectStore('files'));let value;r.onsuccess=()=>value=r.result;tx.oncomplete=()=>resolve(value);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||new Error('LOCAL_MEDIA_WRITE_FAILED'))})}
const get=id=>operation('readonly',s=>s.get(id));const put=row=>operation('readwrite',s=>s.put(row));
async function api(action,body){const response=await fetch('/api/content-router?action='+action,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),result=await response.json();if(!response.ok||!result.ok)throw new Error(result.detail||result.error||'TEMP_MEDIA_API_FAILED');return result}
const locked=(id,work)=>navigator.locks?navigator.locks.request('pt-temp-upload-'+id,work):work();
function preview(row){if(!previews.has(row.id))previews.set(row.id,URL.createObjectURL(row.file));const url=previews.get(row.id),map=aliases();if(map[url]!==row.id||row.remote_url&&map[row.remote_url]!==row.id){map[url]=row.id;if(row.remote_url)map[row.remote_url]=row.id;localStorage.setItem(ALIASES,JSON.stringify(map))}return url}
async function ready(){for(const row of await operation('readonly',s=>s.getAll()))preview(row)}
function restore(value){if(typeof value==='string'){const id=aliases()[value];return id?previews.get(id)||value:value}if(Array.isArray(value))return value.map(restore);if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).map(([k,v])=>[k,restore(v)]));return value}
async function local(file){const digest=await crypto.subtle.digest('SHA-256',await file.arrayBuffer()),id=Array.from(new Uint8Array(digest),n=>n.toString(16).padStart(2,'0')).join('');return locked(id,async()=>{let row=await get(id);if(!row){row={id,file,size:file.size,mime:file.type,created_at:new Date().toISOString(),publications:[]};await put(row)}return {url:preview(row),local_id:id}})}
async function dataUrl(url){const row=await get(aliases()[url]);if(!row)return url;return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(reader.error);reader.readAsDataURL(row.file)})}
async function upload(url){const id=aliases()[url];if(!id){if(/^blob:|^data:/i.test(url))throw new Error('LOCAL_ORIGINAL_MISSING');return url}if(inflight.has(id))return inflight.get(id);
 const work=async()=>{const row=await get(id);if(!row)throw new Error('LOCAL_ORIGINAL_MISSING');if(row.remote_url)return row.remote_url;
  if(row.upload_state==='pending')throw new Error('업로드 결과가 불확실합니다. 임시 미디어 검토 목록과 원격 파일을 확인한 뒤 재시도하세요.');
  row.owner=owner();const intent=await api('temp_media_intent',{sha:id,mime:row.mime,size:row.size});row.pathname=intent.pathname;row.intent=intent.intent;row.upload_state='pending';await put(row);
  const mod=await import('https://esm.sh/@vercel/blob@2.8.0/client?bundle');
  const result=await mod.uploadPresigned(row.pathname,row.file,{access:'public',handleUploadUrl:'/api/content-router?action=media_upload',contentType:row.mime,multipart:row.size>5*1024*1024});
  row.remote_url=result.url;row.upload_state='uploaded';row.uploaded_at=new Date().toISOString();await put(row);preview(row);return result.url};
 const promise=locked(id,work).finally(()=>inflight.delete(id));inflight.set(id,promise);return promise;
}
const payloadUrls=p=>[...(p.media||[]).map(m=>m.url),...(p.image_urls||[]),p.image_url,p.video_url].filter(Boolean);
async function prepare(payload){const result={...payload,_temp_job_id:(payload._temp_job_id||crypto.randomUUID())+':'+tabId};for(const url of payloadUrls(result)){const id=aliases()[url];if(id)await locked(id,async()=>{const row=await get(id);if(!row)throw new Error('LOCAL_ORIGINAL_MISSING');row.active_jobs=row.active_jobs||[];if(!row.active_jobs.some(j=>j.id===result._temp_job_id))row.active_jobs.push({id:result._temp_job_id,started_at:new Date().toISOString()});await put(row)})}if(result.media)result.media=await Promise.all(result.media.map(async m=>({...m,url:await upload(m.url)})));if(result.image_urls)result.image_urls=await Promise.all(result.image_urls.map(upload));for(const k of ['image_url','video_url'])if(result[k])result[k]=await upload(result[k]);return result}
async function published(payload,platform,postId){if(!postId)return;const urls=new Set(payloadUrls(payload));for(const item of await operation('readonly',s=>s.getAll()))if(item.remote_url&&urls.has(item.remote_url))await locked(item.id,async()=>{const row=await get(item.id);row.publications=row.publications||[];if(!row.publications.some(p=>p.platform===platform&&p.post_id===String(postId)))row.publications.push({platform,post_id:String(postId),confirmed_at:new Date().toISOString()});row.active_jobs=(row.active_jobs||[]).filter(j=>j.id!==payload._temp_job_id);row.cleanup_ticket=null;row.cleanup_state='verify_pending';row.next_cleanup_at=0;await put(row)})}
let sweeping=false;
async function sweep(){if(sweeping||!navigator.locks)return;sweeping=true;try{for(const item of await operation('readonly',s=>s.getAll())){if(!item.remote_url||!item.intent||!item.publications?.length||item.next_cleanup_at>Date.now())continue;await locked(item.id,async()=>{const row=await get(item.id);if(!row.remote_url||row.active_jobs?.length)return;row.cleanup_attempts=(row.cleanup_attempts||0)+1;row.last_cleanup_at=new Date().toISOString();row.cleanup_state='checking';await put(row);try{if(!row.cleanup_ticket){const receipt=await api('temp_media_complete',{intent:row.intent,remote_url:row.remote_url,publications:row.publications});row.cleanup_ticket=receipt.ticket;row.not_before=receipt.not_before;await put(row)}if(Date.now()<row.not_before){row.cleanup_state='retention_pending';row.next_cleanup_at=row.not_before;await put(row);return}const result=await api('temp_media_cleanup',{ticket:row.cleanup_ticket});if(result.deleted){row.deleted_remote_url=row.remote_url;row.remote_url=null;row.cleanup_ticket=null;row.upload_state='deleted';row.cleanup_state='deleted';row.publications=[];row.deleted_at=new Date().toISOString();row.next_cleanup_at=0}else{row.cleanup_state=result.reason;row.next_cleanup_at=Date.now()+3600000}row.cleanup_error=null;await put(row)}catch(error){row.cleanup_state='retry_pending';row.cleanup_error=String(error.message);row.next_cleanup_at=Date.now()+Math.min(3600000,60000*2**Math.min(row.cleanup_attempts,6));await put(row)}})}}finally{sweeping=false}}
async function review(){return (await operation('readonly',s=>s.getAll())).filter(r=>r.owner===owner()&&r.upload_state).map(({id,owner,pathname,size,remote_url,upload_state,uploaded_at,publications,cleanup_state,active_jobs,cleanup_attempts,cleanup_error,next_cleanup_at,not_before,deleted_at})=>({id,owner,pathname,size,remote_url,upload_state,uploaded_at,publications,cleanup_state,active_jobs,cleanup_attempts,cleanup_error,next_cleanup_at,not_before,deleted_at,local_original_present:true,eligible_for_automatic_deletion:false}))}
async function reconcile(id,remoteUrl){const row=await get(id);if(!row||row.owner!==owner()||row.upload_state!=='pending')throw new Error('PENDING_UPLOAD_NOT_OWNED');if(remoteUrl){const u=new URL(remoteUrl),base=row.pathname.replace(/\.[^.]+$/,'');if(u.protocol!=='https:'||!/(^|\.)blob\.vercel-storage\.com$/i.test(u.hostname)||!decodeURIComponent(u.pathname).slice(1).startsWith(base))throw new Error('RECOVERY_URL_INVALID')}if(!confirm(remoteUrl?'원격 목록에서 이 파일의 경로·크기를 확인했습니까? 업로드 기록을 복구합니다.':'원격 목록에서 이 임시 경로의 파일이 없음을 확인했습니까? 다시 업로드할 수 있도록 기록만 복구합니다.'))return false;row.remote_url=remoteUrl||null;row.upload_state=remoteUrl?'uploaded':'retry_confirmed';await put(row);preview(row);return true}
async function exportReview(){const rows=await review(),blob=new Blob([JSON.stringify({version:1,created_at:new Date().toISOString(),files:rows},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='temporary-media-review.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
root.LocalMedia={ready,restore,local,dataUrl,upload,prepare,published,review,reconcile,exportReview,sweep};
})(window);
