/* Prompt Thread Growth Engine V2 - filename retained so current index.html keeps working. */
(function(){
const CATS={AI_PROMPT:'AI 프롬프트',AI_TIP:'AI 활용 팁',HOT_ISSUE:'🔥 오늘의 핫이슈',FUN_RELATABLE:'재미·공감형',EXPERIMENT:'실험적인 콘텐츠'};
const QUEUE='pt_publish_queue_v2',FB='pt_content_feedback_v2',PUB='pt_published_v2';
let candidates=[];
function read(k,d=[]){try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch{return d}}
function write(k,v){localStorage.setItem(k,JSON.stringify(v))}
function e(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function addFeedback(x,kind){const a=read(FB);a.unshift({kind,category:x.category,topic:x.topic,hook:x.hook,at:Date.now()});write(FB,a.slice(0,80))}
function getQueue(){return read(QUEUE)}
function saveQueue(a){write(QUEUE,a);renderQueue()}
function published(){return read(PUB)}
function savePublished(x){const a=published();a.unshift(x);write(PUB,a.slice(0,100))}
function bodyOf(i){return document.getElementById(`v2body-${i}`)?.value.trim()||candidates[i]?.body||''}
function hookOf(i){return [...(document.getElementById(`v2hook-${i}`)?.value.trim()||candidates[i]?.hook||'')].slice(0,14).join('')}
async function performanceMemo(){try{const r=await fetch('/api/threads/my-posts',{cache:'no-store'}),j=await r.json();if(!r.ok)return '';const known=new Map(published().map(x=>[String(x.thread_id),x]));return (j.items||[]).map(p=>{const meta=known.get(String(p.id));if(!meta)return null;const m=p.insights||{};return `${meta.category}/${meta.hook}:views=${m.views??'-'},likes=${m.likes??'-'},replies=${m.replies??'-'},reposts=${m.reposts??'-'},quotes=${m.quotes??'-'},shares=${m.shares??'-'}`}).filter(Boolean).slice(0,10).join(' | ')}catch{return ''}}
function ensure(){const old=document.getElementById('autoV1');if(old)old.remove();const dash=document.getElementById('dashboard');if(!dash||document.getElementById('autoV2'))return;dash.insertAdjacentHTML('afterbegin',`<div class="card" id="autoV2" style="margin-bottom:12px"><div class="section"><div><b>✨ 게시물 성장 엔진 V2</b><p class="mut">오늘 이슈 조사 → 내부 아이디어 경쟁 → Red Team 평가 → 최종 5개. 이미지까지 확인한 뒤 채택/게시합니다.</p></div><div style="display:flex;gap:8px;flex-wrap:wrap"><button class="btn p" id="v2gen">강한 후보 5개 생성</button><button class="btn" id="v2images" disabled>🖼 5개 이미지 순차 생성</button></div></div><div id="v2status" class="mut" style="margin-bottom:10px"></div><div id="candidateListV2" class="post-list"></div></div>`);const cal=document.getElementById('calendar');if(cal)cal.innerHTML=`<div class="section"><div><b>발행 대기함</b><p class="mut">이미지까지 검수한 후보만 저장합니다.</p></div><span class="badge" id="queueCountV2">0</span></div><div id="queueListV2" class="post-list"></div>`;document.getElementById('v2gen').onclick=generate;document.getElementById('v2images').onclick=generateAllImages;patchReplyBatch();renderQueue()}
async function generate(){const b=document.getElementById('v2gen'),status=document.getElementById('v2status');b.disabled=true;b.textContent='소재 조사·경쟁 중…';status.textContent='Google Search로 오늘 이슈를 확인하고 내부 후보를 평가합니다.';try{const fb=read(FB).slice(0,30).map(x=>`${x.kind}:${x.category}:${x.topic}:${x.hook}`).join(' | '),perf=await performanceMemo();const r=await fetch('/api/content/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({feedback:fb,performance:perf})});const j=await r.json();if(!r.ok)throw new Error(j.detail||j.error||'GENERATE_FAILED');candidates=j.items||[];status.textContent=`내부 후보 ${j.internal_idea_count||'-'}개에서 최종 ${candidates.length}개 선정 · 핫이슈 Google Search 검증`;renderCandidates();document.getElementById('v2images').disabled=!candidates.length}catch(err){status.textContent='';alert('후보 생성 실패: '+err.message)}finally{b.disabled=false;b.textContent='강한 후보 5개 생성'}}
function scoreHtml(s={}){return `<span class="mut">정지 ${s.stop||0} · 저장 ${s.save||0} · 공유 ${s.share||0} · 댓글 ${s.comment||0} · 팔로우 ${s.follow||0} · 총점 ${s.total||0}</span>`}
function renderCandidates(){const box=document.getElementById('candidateListV2');if(!box)return;box.innerHTML=candidates.map((x,i)=>`<article class="card" id="v2card-${i}"><div class="post-meta"><span class="badge">${e(x.category_label||CATS[x.category])}</span><span class="badge">4:5 이미지 검수 필수</span>${scoreHtml(x.score)}</div><div style="display:grid;grid-template-columns:minmax(0,1fr) minmax(280px,380px);gap:18px;align-items:start" class="v2-layout"><div><label class="mut">후킹 문구 · 최대 14자</label><input id="v2hook-${i}" value="${e(x.hook)}" maxlength="14" style="width:100%;margin:5px 0 10px;background:#0b0e12;border:1px solid var(--l);border-radius:10px;color:white;padding:11px 12px;font-size:18px;font-weight:800"><label class="mut">Threads 본문</label><textarea id="v2body-${i}" maxlength="500" style="width:100%;min-height:190px;margin-top:5px;background:#0b0e12;border:1px solid var(--l);border-radius:10px;color:white;padding:12px;line-height:1.55">${e(x.body)}</textarea><p class="mut">소재 · ${e(x.topic)}</p><p class="mut">추천 이유 · ${e(x.reason)}</p>${x.source_notes?.length?`<p class="mut">팩트 메모 · ${e(x.source_notes.join(' / '))}</p>`:''}<div style="display:flex;gap:8px;flex-wrap:wrap"><button class="btn p" onclick="PostAuto.image(${i})">🖼 이미지 생성</button><button class="btn" onclick="PostAuto.reimage(${i})">🔄 이미지 다시 생성</button><button class="btn" onclick="PostAuto.applyHook(${i})">후킹 적용</button><button class="btn" onclick="PostAuto.variant(${i})">다른 버전</button><button class="btn" onclick="PostAuto.keep(${i})">👍 발행 대기</button><button class="btn p" onclick="PostAuto.now(${i})">🚀 즉시 게시</button><button class="btn" onclick="PostAuto.no(${i})">👎 별로예요</button></div></div><div id="v2image-${i}" class="card" style="padding:10px;min-height:260px;display:grid;place-items:center"><span class="mut">이미지를 생성해 최종 썸네일을 확인하세요.</span></div></div></article>`).join('');if(!document.getElementById('v2responsive'))document.head.insertAdjacentHTML('beforeend','<style id="v2responsive">@media(max-width:900px){.v2-layout{grid-template-columns:1fr!important}}</style>')}
function loadImage(src){return new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=reject;im.src=src})}
function bestLines(ctx,text,maxWidth,fontSize){const chars=[...text.replace(/\s+/g,' ').trim()].slice(0,14),whole=chars.join('');ctx.font=`900 ${fontSize}px "Pretendard","Noto Sans KR","Malgun Gothic",sans-serif`;if(ctx.measureText(whole).width<=maxWidth)return [whole];let best=null;for(let cut=2;cut<=chars.length-2;cut++){const a=chars.slice(0,cut).join('').trim(),b=chars.slice(cut).join('').trim();if(!a||!b||[...b].length===1)continue;const w=Math.max(ctx.measureText(a).width,ctx.measureText(b).width),score=w+Math.abs([...a].length-[...b].length)*20;if(!best||score<best.score)best={lines:[a,b],score}}return best?.lines||[whole]}
async function compose(i){const x=candidates[i];if(!x?.base_image_data_url)throw new Error('이미지를 먼저 생성하세요.');x.hook=hookOf(i);document.getElementById(`v2hook-${i}`).value=x.hook;const im=await loadImage(x.base_image_data_url),canvas=document.createElement('canvas');canvas.width=1080;canvas.height=1350;const ctx=canvas.getContext('2d'),scale=Math.max(canvas.width/im.width,canvas.height/im.height),sw=canvas.width/scale,sh=canvas.height/scale,sx=(im.width-sw)/2,sy=(im.height-sh)/2;ctx.drawImage(im,sx,sy,sw,sh,0,0,canvas.width,canvas.height);const g=ctx.createLinearGradient(0,0,0,500);g.addColorStop(0,'rgba(0,0,0,.78)');g.addColorStop(.55,'rgba(0,0,0,.42)');g.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=g;ctx.fillRect(0,0,canvas.width,520);const maxWidth=936;let size=92,lines;while(size>=58){lines=bestLines(ctx,x.hook,maxWidth,size);ctx.font=`900 ${size}px "Pretendard","Noto Sans KR","Malgun Gothic",sans-serif`;if(lines.length<=2&&lines.every(t=>ctx.measureText(t).width<=maxWidth))break;size-=4}ctx.textBaseline='top';ctx.fillStyle='#fff';ctx.strokeStyle='rgba(0,0,0,.32)';ctx.lineWidth=2;ctx.shadowColor='rgba(0,0,0,.55)';ctx.shadowBlur=10;ctx.shadowOffsetY=3;const lineH=Math.round(size*1.10),startY=92;lines.slice(0,2).forEach((line,n)=>{ctx.strokeText(line,72,startY+n*lineH);ctx.fillText(line,72,startY+n*lineH)});x.final_image_data_url=canvas.toDataURL('image/jpeg',.9);x.image_url=null;renderImagePreview(i)}
function renderImagePreview(i){const x=candidates[i],box=document.getElementById(`v2image-${i}`);if(!box)return;if(!x?.final_image_data_url){box.innerHTML='<span class="mut">이미지를 생성해 최종 썸네일을 확인하세요.</span>';return}box.innerHTML=`<div><img src="${x.final_image_data_url}" alt="완성 썸네일" style="width:100%;aspect-ratio:4/5;object-fit:cover;border-radius:11px;display:block"><p class="mut" style="margin:8px 2px 0">최종 게시 이미지 미리보기 · 이 이미지를 확인한 뒤 채택/게시하세요.</p></div>`}
async function makeImage(i,force=false){const x=candidates[i];if(!x)return;const box=document.getElementById(`v2image-${i}`);box.innerHTML='<span class="mut">Gemini 이미지 제작 중…</span>';if(force)x.variation=(x.variation||1)+1;else x.variation=x.variation||1;x.body=bodyOf(i);x.hook=hookOf(i);try{const r=await fetch('/api/content/image',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({candidate:x,variation:x.variation})});const j=await r.json();if(!r.ok)throw new Error(j.detail||j.error||'IMAGE_FAILED');x.base_image_data_url=`data:${j.mime_type};base64,${j.data}`;x.director_prompt=j.director_prompt;x.image_url=null;await compose(i)}catch(err){box.innerHTML='<span class="mut">이미지 생성 실패</span>';alert('이미지 생성 실패: '+err.message)}}
async function generateAllImages(){const b=document.getElementById('v2images');b.disabled=true;for(let i=0;i<candidates.length;i++){b.textContent=`이미지 ${i+1}/${candidates.length} 생성 중`;await makeImage(i,false)}b.textContent='🖼 5개 이미지 순차 생성';b.disabled=false}
async function uploadFinal(i){const x=candidates[i];if(x.image_url)return x.image_url;if(!x.final_image_data_url)throw new Error('최종 이미지를 먼저 생성하고 확인하세요.');const r=await fetch('/api/content/store-image',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({candidate_id:x.id,data_url:x.final_image_data_url})});const j=await r.json();if(!r.ok){if(j.error==='BLOB_NOT_CONFIGURED')throw new Error('Vercel Blob이 아직 연결되지 않았습니다. Storage에서 Public Blob을 연결하세요.');throw new Error(j.detail||j.error||'IMAGE_UPLOAD_FAILED')}x.image_url=j.url;return j.url}
async function keep(i){const x=candidates[i];if(!x.final_image_data_url)return alert('먼저 이미지를 생성해서 최종 썸네일을 확인해 주세요.');try{x.body=bodyOf(i);x.hook=hookOf(i);await compose(i);const url=await uploadFinal(i),stored={...x,image_url:url,kept_at:Date.now()};delete stored.base_image_data_url;delete stored.final_image_data_url;const a=getQueue();a.unshift(stored);saveQueue(a);addFeedback(x,'LIKE');alert('이미지까지 포함해 발행 대기함에 저장했습니다. ✅')}catch(err){alert('발행 대기 저장 실패: '+err.message)}}
async function now(i){const x=candidates[i];if(!x.final_image_data_url)return alert('즉시 게시 전에 이미지를 생성해서 눈으로 확인해 주세요.');x.body=bodyOf(i);x.hook=hookOf(i);try{await compose(i);if(!confirm(`지금 보이는 이미지와 본문 그대로 Threads에 게시할까요?\n\n${x.hook}`))return;const url=await uploadFinal(i);const r=await fetch('/api/threads/publish',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:x.body,image_url:url})});const j=await r.json();if(!r.ok)throw new Error(j?.detail?.message||j.error||'PUBLISH_FAILED');addFeedback(x,'PUBLISHED');savePublished({thread_id:j.id,category:x.category,topic:x.topic,hook:x.hook,published_at:Date.now(),image_url:url});alert('이미지 + 본문 Threads 게시 완료 ✅')}catch(err){alert('게시 실패: '+err.message)}}
async function variant(i){const x=candidates[i],card=document.getElementById(`v2card-${i}`);card.style.opacity='.65';try{x.body=bodyOf(i);x.hook=hookOf(i);const r=await fetch('/api/content/variant',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({candidate:x})});const j=await r.json();if(!r.ok)throw new Error(j.detail||j.error||'VARIANT_FAILED');candidates[i]=j.item;candidates[i].variation=1;addFeedback(x,'VARIANT');renderCandidates()}catch(err){alert('다른 버전 생성 실패: '+err.message)}finally{card.style.opacity=''}}
function no(i){addFeedback(candidates[i],'DISLIKE');candidates.splice(i,1);renderCandidates();document.getElementById('v2images').disabled=!candidates.length}
async function applyHook(i){try{await compose(i)}catch(err){alert(err.message)}}
function renderQueue(){const a=getQueue(),count=document.getElementById('queueCountV2'),box=document.getElementById('queueListV2');if(count)count.textContent=a.length;if(!box)return;box.innerHTML=a.length?a.map((x,i)=>`<article class="card"><div style="display:grid;grid-template-columns:160px 1fr;gap:14px"><img src="${e(x.image_url)}" style="width:160px;aspect-ratio:4/5;object-fit:cover;border-radius:10px"><div><span class="badge">${e(x.category_label||CATS[x.category])}</span><h3>${e(x.hook)}</h3><div class="post-text">${e(x.body)}</div><div style="margin-top:10px;display:flex;gap:8px"><button class="btn p" onclick="PostAuto.publishQueue(${i})">🚀 지금 게시</button><button class="btn" onclick="PostAuto.drop(${i})">제거</button></div></div></div></article>`).join(''):'<div class="card empty"><div><b>발행 대기 없음</b>이미지를 검수하고 👍한 후보가 여기에 저장됩니다.</div></div>'}
async function publishQueue(i){const a=getQueue(),x=a[i];if(!x)return;if(!confirm(`"${x.hook}" 지금 게시할까요?`))return;const r=await fetch('/api/threads/publish',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:x.body,image_url:x.image_url})});const j=await r.json();if(!r.ok)return alert('게시 실패: '+(j?.detail?.message||j.error));savePublished({thread_id:j.id,category:x.category,topic:x.topic,hook:x.hook,published_at:Date.now(),image_url:x.image_url});addFeedback(x,'PUBLISHED');a.splice(i,1);saveQueue(a);alert('게시 완료 ✅')}
function drop(i){const a=getQueue();a.splice(i,1);saveQueue(a)}
function patchReplyBatch(){const note=document.querySelector('#replies .section p.mut');if(note)note.textContent='최근 2일 댓글만 표시합니다. 이미 답장한 댓글은 제외하고 미응답 전체를 천천히 순차 처리합니다.';if(typeof updateBatchButton==='function'){updateBatchButton=function(){const items=Array.isArray(window._replyItems)?window._replyItems:[],eligible=items.filter(x=>!x.review_required&&!x.already_replied),n=eligible.length,b=document.getElementById('batchReply'),note=document.getElementById('batchNote');b.disabled=!n||window._replyHistoryAvailable===false||window._batchRunning;b.textContent=window._batchRunning?'일괄 답장 처리 중…':(n?`일괄 승인 후 답장 (${n})`:'일괄 승인 후 답장');note.textContent=window._replyHistoryAvailable===false?'답장 이력을 확인하지 못해 일괄 답장을 비활성화했습니다.':`최근 2일 미응답 ${eligible.length}개 · API 보호를 위해 한 개씩 순차 처리합니다.`}}const b=document.getElementById('batchReply');if(!b)return;b.onclick=async()=>{if(window._batchRunning||window._replyHistoryAvailable===false)return;const all=Array.isArray(window._replyItems)?window._replyItems:[],targets=[];all.forEach((item,i)=>{if(item.review_required||item.already_replied)return;const input=document.getElementById(`replyText-${i}`),text=input?.value.trim();if(text)targets.push({i,id:item.id,text})});if(!targets.length)return;if(!confirm(`${targets.length}개 미응답 댓글을 천천히 순차 답장할까요?\n\n스팸/욕설·이미 답장한 댓글은 제외됩니다.`))return;window._batchRunning=true;updateBatchButton();let success=0,failed=0;for(let n=0;n<targets.length;n++){const t=targets[n];b.textContent=`일괄 답장 ${n+1}/${targets.length}`;try{await postReply(t.id,t.text);markReplyDone(t.i,t.id,t.text);success++}catch{failed++}if(n<targets.length-1)await new Promise(r=>setTimeout(r,500))}window._batchRunning=false;updateBatchButton();alert(`일괄 답장 완료 · 성공 ${success} / 실패 ${failed}`);await syncReplies(currentPostIds).catch(()=>{})};setTimeout(()=>{try{updateBatchButton()}catch{}},100)}
window.PostAuto={image:(i)=>makeImage(i,false),reimage:(i)=>makeImage(i,true),applyHook,keep,now,variant,no,drop,publishQueue};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',ensure);else ensure();
})();
