const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),{webcrypto}=require('node:crypto');
const source=fs.readFileSync(require('node:path').join(__dirname,'../local-media.js'),'utf8');
function harness(shared={rows:new Map(),storage:new Map()},fail=false){
 const calls=[],apiCalls=[];let counter=0;const ctx={window:{},console,Blob,FileReader:class{},crypto:webcrypto,navigator:{},setTimeout,URL:{createObjectURL:()=>`blob:${webcrypto.randomUUID()}-${++counter}`,revokeObjectURL(){}},localStorage:{getItem:k=>shared.storage.get(k)||null,setItem:(k,v)=>shared.storage.set(k,v)},mockStore:{get:id=>structuredClone(shared.rows.get(id)),getAll:()=>structuredClone([...shared.rows.values()]),put:r=>{shared.rows.set(r.id,structuredClone(r));return r.id}},async fetch(url,options){const body=JSON.parse(options.body);apiCalls.push({url,body});let result;if(url.endsWith('temp_media_intent'))result={pathname:`content-master/temp-${webcrypto.randomUUID()}/${body.sha}.jpg`,intent:'mock-intent'};else if(url.endsWith('temp_media_complete'))result={ticket:'mock-ticket',not_before:0};else result={deleted:true};return {ok:true,async json(){return {ok:true,...result}}}},mockModule:{async uploadPresigned(path,file){calls.push({path,size:file.size});if(fail)throw new Error('network interruption');return {url:'https://test.public.blob.vercel-storage.com/'+path}}}};
 // Mock the durable storage adapter and SDK only; execute production lifecycle code.
 const code=source.replace(/async function operation\(mode,run\)\{[\s\S]*?\nconst get=/,'async function operation(mode,run){return run(mockStore)}\nconst get=').replace("await import('https://esm.sh/@vercel/blob@2.8.0/client?bundle')",'mockModule');
 vm.runInNewContext(code,ctx);return {api:ctx.window.LocalMedia,calls,shared,apiCalls,ctx};
}
const image=()=>new Blob(['jpeg-source'],{type:'image/jpeg'});
test('local file selection preserves bytes without remote upload',async()=>{const h=harness(),m=await h.api.local(image());assert.match(m.url,/^blob:/);assert.equal(h.calls.length,0);assert.equal(await [...h.shared.rows.values()][0].file.text(),'jpeg-source')});
test('concurrent and repeated upload of identical bytes uses one remote object',async()=>{const h=harness(),a=await h.api.local(image()),b=await h.api.local(image());const urls=await Promise.all([h.api.upload(a.url),h.api.upload(b.url)]);assert.equal(urls[0],urls[1]);assert.equal(await h.api.upload(a.url),urls[0]);assert.equal(h.calls.length,1);assert.match(h.calls[0].path,/^content-master\/temp-[a-f0-9-]+\/[a-f0-9]{64}\.jpg$/)});
test('new page restores old preview URL and reuses durable upload receipt',async()=>{const h=harness(),a=await h.api.local(image()),remote=await h.api.upload(a.url),again=harness(h.shared);await again.api.ready();const restored=again.api.restore({media:[{url:a.url}]});assert.notEqual(restored.media[0].url,a.url);assert.equal(await again.api.upload(restored.media[0].url),remote);assert.equal(again.calls.length,0)});
test('ambiguous upload failure blocks duplicate retry after reload',async()=>{const h=harness(undefined,true),a=await h.api.local(image());await assert.rejects(h.api.upload(a.url),/network interruption/);const again=harness(h.shared);await again.api.ready();await assert.rejects(again.api.upload(again.api.restore(a.url)),/불확실/);assert.equal(again.calls.length,0);assert.equal((await again.api.review())[0].upload_state,'pending')});
test('prepare preserves Instagram prompt mapping and uploads selected media only',async()=>{const h=harness(),a=await h.api.local(image());await h.api.local(new Blob(['unused-cut'],{type:'image/jpeg'}));const p=await h.api.prepare({media:[{url:a.url,type:'image'}],request_id:'unchanged-request',content_id:'content',content_type:'AI_TIP',reply_prompt:'DM text',caption:'caption'});assert.equal(p.reply_prompt,'DM text');assert.equal(p.content_id,'content');assert.equal(p.request_id,'unchanged-request');assert.match(p.media[0].url,/^https:/);assert.equal(h.calls.length,1)});
test('publication receipt is review-only, deduplicated, and never deletes',async()=>{const h=harness(),a=await h.api.local(image()),p=await h.api.prepare({image_urls:[a.url]});await h.api.published(p,'instagram','123');await h.api.published(p,'instagram','123');await h.api.published(p,'threads','456');const rows=await h.api.review();assert.equal(rows.length,1);assert.equal(rows[0].publications.length,2);assert.equal(rows[0].eligible_for_automatic_deletion,false);assert.equal(h.shared.rows.size,1)});
test('legacy HTTPS URLs pass through and are excluded from owned cleanup manifest',async()=>{const h=harness();assert.equal(await h.api.upload('https://old.public.blob.vercel-storage.com/legacy.jpg'),'https://old.public.blob.vercel-storage.com/legacy.jpg');assert.equal((await h.api.review()).length,0);assert.equal(h.calls.length,0)});
test('unknown stale browser URLs fail closed',async()=>{await assert.rejects(harness().api.upload('blob:missing'),/LOCAL_ORIGINAL_MISSING/)});
test('sweep blocks shared file until all publication jobs complete',async()=>{const h=harness();h.ctx.navigator.locks={request:async(name,fn)=>fn()};const a=await h.api.local(image()),first=await h.api.prepare({_temp_job_id:'one',image_url:a.url}),second=await h.api.prepare({_temp_job_id:'two',image_url:a.url});await h.api.published(first,'instagram','123');await h.api.sweep();assert.equal(h.apiCalls.filter(c=>c.url.endsWith('temp_media_cleanup')).length,0);await h.api.published(second,'threads','456');await h.api.sweep();assert.equal(h.apiCalls.filter(c=>c.url.endsWith('temp_media_cleanup')).length,1);const row=[...h.shared.rows.values()][0];assert.equal(row.remote_url,null);assert.equal(row.upload_state,'deleted');assert.equal(await row.file.text(),'jpeg-source')});
test('delete failure persists retry and resumes after page restart',async()=>{const h=harness();h.ctx.navigator.locks={request:async(name,fn)=>fn()};const a=await h.api.local(image()),p=await h.api.prepare({_temp_job_id:'job',image_url:a.url});await h.api.published(p,'threads','123');const fetch=h.ctx.fetch;h.ctx.fetch=async(url,opts)=>{if(url.endsWith('temp_media_cleanup'))throw new Error('offline');return fetch(url,opts)};await h.api.sweep();let row=[...h.shared.rows.values()][0];assert.equal(row.cleanup_state,'retry_pending');assert.equal(row.cleanup_attempts,1);assert.ok(row.remote_url);row.next_cleanup_at=0;h.shared.rows.set(row.id,row);const again=harness(h.shared);again.ctx.navigator.locks={request:async(name,fn)=>fn()};await again.api.sweep();row=[...h.shared.rows.values()][0];assert.equal(row.cleanup_state,'deleted');assert.equal(row.cleanup_attempts,2)});
test('no Web Locks means no automatic deletion',async()=>{const h=harness(),a=await h.api.local(image()),p=await h.api.prepare({image_url:a.url});await h.api.published(p,'threads','123');await h.api.sweep();assert.equal(h.apiCalls.filter(c=>c.url.endsWith('temp_media_cleanup')).length,0)});
test('same job identity in two tabs has independent active references',async()=>{const first=harness(),second=harness(first.shared);for(const h of [first,second])h.ctx.navigator.locks={request:async(name,fn)=>fn()};const a=await first.api.local(image());await second.api.ready();const p1=await first.api.prepare({_temp_job_id:'same-job',image_url:a.url}),p2=await second.api.prepare({_temp_job_id:'same-job',image_url:second.api.restore(a.url)});assert.notEqual(p1._temp_job_id,p2._temp_job_id);await first.api.published(p1,'threads','123');await first.api.sweep();assert.equal([...first.shared.rows.values()][0].active_jobs.length,1);assert.ok([...first.shared.rows.values()][0].remote_url);await second.api.published(p2,'threads','456');await second.api.sweep();assert.equal([...first.shared.rows.values()][0].remote_url,null)});
