const test=require('node:test'),assert=require('node:assert/strict'),{createTemporaryMediaService}=require('../lib/temp-media-cleanup.cjs');
function harness(){let time=1000000,enabled=true,media={id:'123',permalink:'https://www.threads.com/@test/post/123',urls:['https://scontent.cdninstagram.com/media.jpg']};const deleted=[],objects=new Map();const api=createTemporaryMediaService({secret:()=> 'test-secret-only',enabled:()=>enabled,retentionHours:()=>24,now:()=>time,blob:{async head(url){if(!objects.has(url))throw Object.assign(new Error('not found'),{name:'BlobNotFoundError'});return objects.get(url)},async del(url){deleted.push(url);objects.delete(url)}},verifyPublication:async()=>media});const input={sha:'a'.repeat(64),mime:'image/jpeg',size:10};async function complete(){const intent=api.intent(input),url='https://test.public.blob.vercel-storage.com/'+intent.pathname;objects.set(url,{url,pathname:intent.pathname,size:10});const done=await api.complete({...intent,remote_url:url,publications:[{platform:'threads',post_id:'123'}]});return {intent,url,...done}}return {api,objects,deleted,complete,advance:()=>time+=86400001,disable:()=>enabled=false,media:value=>media=value}}
test('only verified temporary URL is deleted after policy hold and platform recheck',async()=>{const h=harness(),r=await h.complete();assert.equal((await h.api.cleanup(r)).reason,'RETENTION_PENDING');assert.equal(h.deleted.length,0);h.advance();assert.equal((await h.api.cleanup(r)).deleted,true);assert.deepEqual(h.deleted,[r.url]);assert.equal((await h.api.cleanup(r)).already_absent,true)});
test('disabled policy never deletes',async()=>{const h=harness(),r=await h.complete();h.advance();h.disable();assert.equal((await h.api.cleanup(r)).reason,'AUTO_CLEANUP_DISABLED');assert.equal(h.deleted.length,0)});
test('forged receipt and arbitrary legacy path cannot authorize deletion',async()=>{const h=harness(),r=await h.complete();await assert.rejects(h.api.cleanup({ticket:r.ticket+'x'}),/TEMP_RECEIPT_INVALID/);await assert.rejects(h.api.complete({...r.intent,remote_url:'https://test.public.blob.vercel-storage.com/threads-growth/old.jpg',publications:[{platform:'threads',post_id:'123'}]}),/TEMP_PATH_INVALID/);assert.equal(h.deleted.length,0)});
test('SSRF hosts, credentials, queries, traversal and lookalike prefixes reject before head',async()=>{const h=harness(),r=await h.complete();for(const url of ['http://127.0.0.1/a','https://user@test.public.blob.vercel-storage.com/'+r.intent.pathname,r.url+'?x=1',r.url.replace('/temp-','/other-temp-'),r.url.replace('.com/','.com/../')])assert.throws(()=>h.api.validateUrl(url,r.intent.pathname));assert.equal(h.deleted.length,0)});
test('head metadata mismatch prevents completion',async()=>{const h=harness(),r=await h.complete();h.objects.set(r.url,{url:r.url,pathname:r.intent.pathname,size:11});await assert.rejects(h.api.complete({...r.intent,remote_url:r.url,publications:[{platform:'threads',post_id:'123'}]}),/TEMP_OBJECT_MISMATCH/)});
test('missing platform media or Blob source remains blocks deletion even after delay',async()=>{const h=harness(),r=await h.complete();h.advance();h.media({id:'123',permalink:'https://threads.com/post/123',urls:[r.url]});await assert.rejects(h.api.cleanup(r),/PUBLICATION_NOT_CONFIRMED/);assert.equal(h.deleted.length,0)});
test('unsupported or malformed publication proof cannot mint cleanup ticket',async()=>{const h=harness(),r=await h.complete();for(const p of [{platform:'facebook',post_id:'123'},{platform:'threads',post_id:'../me'}])await assert.rejects(h.api.complete({...r.intent,remote_url:r.url,publications:[p]}),/PUBLICATION_UNSUPPORTED/)});
